name: Commit CI

on:
  push:
    paths:
      - "core/**"
      - "server_app/**"
      - "test_cases/**"
  pull_request:
    paths:
      - "core/**"
      - "server_app/**"
      - "test_cases/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      IS_RUNNING_CI: "1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl git build-essential cmake libmongoc-1.0-0 libbson-1.0-0 libgflags-dev libssl-dev libsasl2-dev libzstd-dev libspdlog-dev libgtest-dev libboost-all-dev make g++
        bash install_library.sh

    - name: Run build script
      run: bash build_bash.sh

    - name: Run tests
      run: bash test_bash.sh